server:
  port: ${PORT:9091}
message: Configuracion de Usuario roles en el servidor levantado

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789
    url: jdbc:mysql://localhost:3306/logi_market_dba?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: "optional:configserver:"  # Esto asegura que la configuración sea opcional

cloud:
  config:
    uri: http://localhost:9090
